app:
  version: 1.0.0

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

server:
  port: 8080